use aserradero;
SELECT * FROM ENTRADA_MADERA;


SELECT * FROM COSTO_MADERA_ENTRADA;
SELECT * FROM ENTRADA_MADERA;
SELECT id_administrador, (select concat (nombre,' ',apellido_paterno,' ',apellido_materno) as nombre FROM PERSONA WHERE id_persona = id_administrador)as nombre FROM ADMINISTRADOR;

SELECT * FROM VISTA_ENTRADA_MADERA;


SELECT * FROM VISTA_ENTRADA_MADERA_COSTO;
SELECT * FROM VISTA_ENTRADA_MADERA;



SELECT * FROM INVENTARIO_MADERA_ENTRADA;
SELECT * FROM VISTA_ENTRADA_MADERA;
select id_entrada from ENTRADA_MADERA;
delete from INVENTARIO_MADERA_ENTRADA where id_administrador='PAXA20160913HOCSXN';
SELECT * FROM ENTRADA_MADERA;
describe INVENTARIO_MADERA_ENTRADA;

SELECT * FROM VISTA_ENTRADA_MADERA_ROLLO;
SELECT * FROM VISTA_SALIDA_MADERA_ROLLO;
SELECT * FROM SALIDA_MADERA_ROLLO;
SELECT * FROM ENTRADA_MADERA_ROLLO;
DROP TRIGGER IF EXISTS ACTUALIZAR_SALIDA_MADERA_ROLLO;

describe VISTA_PRODUCCION_MADERA;
select * from COSTO_MADERA;
SELECT * FROM VISTA_PRODUCCION_MADERA;
SELECT * FROM PRODUCCION_MADERA;
DROP TRIGGER IF EXISTS AGREGAR_INVENTARIO_PRODUCCION;

SELECT * FROM PRODUCCION_MADERA;
SELECT * FROM INVENTARIO_MADERA_PRODUCCION;
<<<<<<< HEAD



DESCRIBE ANTICIPO_CLIENTE;

=======
>>>>>>> 5b1a42d1904171309caaab46d29808a406d82328
